from io import StringIO

from polyA import load_alignments

# TODO: Add test files that use different strand values
# TODO: Add test files where start > stop
# TODO: Add test files where consensus_start > consensus_stop

alignment1 = StringIO("""Align: AluYj4	1-AluJr_311-AluYb8_629-AluSz6	1049	+	1	309	1	311
>1-AluJr_311-AluYb8_629-AluSz6
GGCCTTGCGAGGTGGGTCACGNCANNTGTAATCCCACTAATTTGGCCGGCCGAGGGTGGC
GGATC----GTTCANNNAGATTTTGAGGCCAGCCTGGGGGACCTANNN--GCGAGAGGCC
GTCTCAACCAAAAATATTTATG-TTCGCCGGACTTGGTGGCGCGCGGCTGCAGTCCCAGC
TACTCGGGTGGCTGAGGCGGGAGGAAGGCTTGAGCCGAGGAGTTCNNNAAGCCTGCAG--
AGCTATGTTCGGGCCATTA---TCTAGCCTGTGCGACAGAGCGAAACTC----TCAAAAA
AAAANAAAATAAAAANNAAAAACAA
>AluYj4
GGCCGGGCGCGGTGGCTCGCGCC---TGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGC
GGATCACGAGGTCAGG-AGATC--GAGACCATCCTGG-----CTAACACGGTGAAACCCC
GTCTCTACTAAAAATGCAAAAAATTAGCCGGGCGTGGTGGCGGGCGCCTGTAGTCCCAGC
TGCTCGGGAGGCTGAGGCAGGAGAATGGCGTGAACCCGGGAG---GCGGAGCTTGCAGTG
AGCCGAGATCGTGCCACTGCACTCCAGCCTGGGCGACAGAGCGAGACTCCGTCTCAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA
Align: AluYi6_4d	1-AluJr_311-AluYb8_629-AluSz6	993	+	1	309	1	311
>1-AluJr_311-AluYb8_629-AluSz6
GGCCTTGCGAGGTGGGTCACGNCANNTGTAATCCCACTAATTTGGCCGGCCGAGGGTGGC
GGATC----GTTCANNNAGATTTTGAGGCCAGCCTGGGGGACCTANNN--GCGAGAGGCC
GTCTCAACCAAAAATATTTATG-TTCGCCGGACTTGGTGGCGCGCGGCTGCAGTCCCAGC
TACTCGGGTGGCTGAGGCGGGAGGAAGGCTTGAGCCGAGGAGTTCNNNAAGCCTGCAG--
AGCTATGTTCGGGCCATTA---TCTAGCCTGTGCGACAGAGCGAAACTC----TCAAAAA
AAAANAAAATAAAAANNAAAAACAA
>AluYi6_4d
GGCCGGGCGCGGTGGCTCACGC---TTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGC
GGATCACGAGGTCAGG-AGATC--GAGACCATCCTGG-----CTAACACGGTGAAACCCC
GTCTCTACTAAAAATACAAAAAATTAGCCGGGCGTGGTGGCGGGCGCCTGTAGTCCCAGC
TACTCGGGAGGCTGAGGCAGGAGAATGGCGTGAACCTGGGAG---GCGGAGCTTGCAGTG
AGCCGAGATTGCGCCACTGCACTCCCACCTGGGCCACAGAGCGAGACTCCGTCTCAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAA""")


def test_load_alignments_1():
    skip, first, second = load_alignments(alignment1)

    assert first.subfamily == "AluYj4"
    assert second.subfamily == "AluYi6_4d"

    assert first.sequence.startswith("GGCCTTGCGA")
    assert second.sequence.startswith("GGCCTTGCGA")

    assert first.subfamily_sequence.startswith(
        "GGCCGGGCGCGGTGGCTCGCGCC---TGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGC"
    )
    assert second.subfamily_sequence.startswith(
        "GGCCGGGCGCGGTGGCTCACGC---TTGTAATCCCAGCACTTTGGGAGGCCGAGGCGGGC"
    )

    assert first.score == 1049
    assert second.score == 993

    assert first.start == 1
    assert second.start == 1

    assert first.stop == 309
    assert second.stop == 309

    assert first.consensus_start == 1
    assert second.consensus_start == 1

    assert first.consensus_stop == 311
    assert second.consensus_stop == 311
