name: PolyA CI

on: [push, pull_request]

jobs:
  check-fast:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/polya-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make setup-dev check-fast

  check-slow:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/polya-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make setup-dev check-slow

  check-format:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/polya-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make setup-dev check-format

  check-lints:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/polya-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make setup-dev check-lints

  check-types:
    runs-on: ubuntu-20.04
    container:
      image: traviswheelerlab/polya-build
      volumes:
        - ${{ github.workspace }}:/code
    steps:
      - uses: actions/checkout@v1
      - run: make setup-dev check-types

